name: production deployment
on: push
jobs:
 if: github.ref == 'refs/heads/main'
     github.event_name == 'push' &&
     github.actor == 'Kiran-DP-08' 
 runs-on: ubuntu-latest
 steps:
   - name: deploy 
     run: echo "Deploying to production"   
