name: context demo 
on : push
jobs:
  text:
    runs-on: ubuntu-latest
    steps:
      - name: print context variables
        run: |
         echo "GITHUB_REPOSITORY: ${{ github.repository }}"
         echo "GITHUB_REF: ${{ github.ref }}"
         echo "GITHUB_SHA: ${{ github.sha }}"
         echo "GITHUB_ACTOR: ${{ github.actor }}"
         echo "GITHUB_EVENT_NAME: ${{ github.event_name }}"